server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: productservice
          uri: http://localhost:8901/
          predicates:
            - Path=/product/**
        - id: stockservice1
          uri: http://localhost:8900/
          predicates:
            - Path=/stock/**
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/