server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka,
                   http://eurekaserver2:8762/eureka

spring:
  application:
    name: StockService